name: Release

on:
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.4.15"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ env.UV_VERSION }}
    
    - name: Get version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Update version in pyproject.toml
      run: |
        uv run python -c "
        import re
        with open('pyproject.toml', 'r') as f:
            content = f.read()
        content = re.sub(r'version = \"[^\"]*\"', f'version = \"${{ steps.get_version.outputs.version }}\"', content)
        with open('pyproject.toml', 'w') as f:
            f.write(content)
        "
    
    - name: Install build dependencies
      run: |
        uv sync --dev
        uv add --dev build twine
    
    - name: Build distribution
      run: |
        uv build
    
    - name: Verify distribution
      run: |
        uv run twine check dist/*
        
        # List built files
        echo "Built files:"
        ls -la dist/
        
        # Get file sizes
        echo "File sizes:"
        du -h dist/*
    
    - name: Generate release notes
      id: release_notes
      run: |
        echo "## Changes" > RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        
        # Get the previous tag
        PREV_TAG=$(git tag --sort=-version:refname | grep -v "${{ steps.get_version.outputs.tag }}" | head -n 1)
        
        if [ ! -z "$PREV_TAG" ]; then
          # Get commits since previous tag
          git log --pretty=format:"- %s" $PREV_TAG..${{ steps.get_version.outputs.tag }} >> RELEASE_NOTES.md
        else
          echo "- Initial release" >> RELEASE_NOTES.md
        fi
        
        # Output the content for GitHub using a unique delimiter
        delimiter=$(openssl rand -hex 8)
        {
          echo "release_notes<<${delimiter}"
          cat RELEASE_NOTES.md
          echo "${delimiter}"
        } >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        name: Release ${{ steps.get_version.outputs.tag }}
        body: ${{ steps.release_notes.outputs.release_notes }}
        files: |
          dist/*
          install.sh
          install-pip.sh
          install-url.py
        draft: false
        prerelease: ${{ contains(steps.get_version.outputs.tag, 'rc') || contains(steps.get_version.outputs.tag, 'alpha') || contains(steps.get_version.outputs.tag, 'beta') }}
        make_latest: ${{ !contains(steps.get_version.outputs.tag, 'rc') && !contains(steps.get_version.outputs.tag, 'alpha') && !contains(steps.get_version.outputs.tag, 'beta') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        if [ -z "$TWINE_PASSWORD" ]; then
          echo "⚠️ PYPI_TOKEN not set, skipping PyPI upload"
          echo "To enable PyPI uploads, add your PyPI token as a secret named PYPI_TOKEN"
        else
          echo "📦 Uploading to PyPI..."
          uv run twine upload dist/* --non-interactive
          echo "✅ Successfully uploaded to PyPI"
        fi
    
    - name: Update installation badge
      run: |
        echo "✅ Release ${{ steps.get_version.outputs.tag }} created successfully!"
        echo ""
        echo "📦 Distribution files:"
        ls -la dist/
        echo ""
        echo "🔗 Installation commands:"
        echo "  uv tool install r4r"
        echo "  pip install r4r"
        echo ""
        echo "🎉 Release is now available at:"
        echo "  https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.tag }}"
        
        # Check if PyPI upload was successful
        if [ ! -z "${{ secrets.PYPI_TOKEN }}" ]; then
          echo "  https://pypi.org/project/r4r/${{ steps.get_version.outputs.version }}/"
        fi